### ISSUE TITLE
Crash on /timings paste

### ISSUE THREAD

**Issue by ghost** [AtlasMediaGroup/Scissors#55]
Stacktrace:  
```bash
[13:18:36 INFO]: maniaplay issued server command: /timings paste
[13:18:36 INFO]: Preparing Timings Report...
[13:18:36 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfiguration org.bukkit.Server$Spigot.getScissorsConfig()'
     at co.aikar.timings.TimingsExport.reportTimings(TimingsExport.java:245) ~[scissors-1.19.jar:git-Scissors-82]
     at org.bukkit.craftbukkit.v1_19_R1.util.CraftMagicNumbers.reportTimings(CraftMagicNumbers.java:223) ~[scissors-1.19.jar:git-Scissors-82]
     at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:79) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Scissors-82]
     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1486) ~[scissors-1.19.jar:git-Scissors-82]
     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[scissors-1.19.jar:git-Scissors-82]
     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[scissors-1.19.jar:git-Scissors-82]
     at java.lang.Thread.run(Thread.java:833) ~[?:?]
 ```

**Comment by MaybeTrollface** [comment]
have you tried restarting it?
